### ISSUE TITLE
Missing Idempotency for one agent installation

### ISSUE THREAD

**Issue by alexfrosa** [Dynatrace/Dynatrace-OneAgent-Chef#1]
The cookbook is not checking if the oneagent is already installed and every time the chef-client converges it installs again. It is easy to fix it, just include something like this in each recipe resource.

not_if 'test -d /opt/dynatrace/oneagent'

Example:

script "dynatrace-oneagent-Linux" do
   interpreter "sh"
   user "root"
   code <<-EOH
      /bin/sh #{tmp_dir}/#{filename}
   EOH
   not_if 'test -d /opt/dynatrace/oneagent'
end

**Comment by sarahbakal** [comment]
Also for the remote_file and file or you end up downloading and deleting the script every client run

**Comment by Here-Be-Dragons** [comment]
This appears to still be an issue.  Is this cookbook abandoned?

**Comment by luisr-escobar** [comment]
Fixed on [#9 ](https://github.com/Dynatrace/Dynatrace-OneAgent-Chef/pull/9)
