### ISSUE TITLE
top level attributes

### ISSUE THREAD

**Issue by sarahbakal** [Dynatrace/Dynatrace-OneAgent-Chef#6]
not preferred:
node[‘download_link’]

preferred:
node['dynatraceoneagent’][‘download_link’]

This helps prevent another cookbook using the same generic default['download_link'], or worse override['download_link']

**Comment by luisr-escobar** [comment]
Fixed on [#9 ](https://github.com/Dynatrace/Dynatrace-OneAgent-Chef/pull/9)
