### ISSUE TITLE
Windows installer not up to date

### ISSUE THREAD

**Issue by MikeL9286** [Dynatrace/Dynatrace-OneAgent-Chef#8]
Current installation method from dynatrace is supposedly to install via the sh script extracted from the downloaded exe. The current version of this cookbook attempts to run the MSI installer directly in interactive mode.

**Comment by luisr-escobar** [comment]
Fixed on [#9 ](https://github.com/Dynatrace/Dynatrace-OneAgent-Chef/pull/9)
